server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
   context-path: /

spring:
  mail:
    default-encoding: utf-8
    host: k
    username: k
    password: k
  #解决swagger2与springboot版本不兼容
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.0.0.130:3306/oawx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: k
      password: k
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: 10.0.0.130
    port: 6379
    password: 7wen
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: 10.0.0.130
      port: 27017
      database: k
      authentication-database: k
      username: k
      password: k

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.wen.oawxapi.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.wen.oawxapi.dao: warn
#  pattern:
#    console: "%d{HH:mm:ss} %-5level %msg%n"

oa:
  jwt:
    #秘钥
    secret: oawx-wen
    #过期时间(天)
    expire: 5
    #缓存过期时间(天)
    cache-expire: 10
  wx:
    #appid
    appId: k
    secret: k
  face:
    #请求url
    identify-url: 192.168.31.149:5000/face/identify
    model-url: 192.168.31.149:5000/face/model
  email:
    system: k
    hr: k
  image-folder: classpath*:upload